'use strict';

angular.module('trainingApp', [
    'ngAnimate',
    'ngAria',
    'ngCookies',
    'ngMaterial',
    'ngMessages',
    'ngRoute',
    'core',
    'myAboutCard',
    'myApiEndpointsList',
    'myAuthTabs',
    'myErrorCard',
    'myGreetCard',
    'myLegalCard',
    'myLoginCard',
    'myLoginPrompt',
    'myProfileDetails',
    'myProfileHeader',
    'myProfileHobbies',
    'myProfileTimeline',
    'mySidenav',
    'myTables',
    'myToolbar',
    'myUserList',
    'myUserMaps',
    'myUserStatistics',
    'myUserRegistration',
    'myUserStatistics'
]);
