@echo off

pushd %~dp0

echo Creating users...
sqlite3 TrainingApp.db ".read sql/users.sql"
echo Creating accounts...
sqlite3 TrainingApp.db ".read sql/accounts.sql"
echo Creating user_images...
sqlite3 TrainingApp.db ".read sql/user_images.sql"
echo Creating hobbies...
sqlite3 TrainingApp.db ".read sql/hobbies.sql"
echo Creating user_hobbies...
sqlite3 TrainingApp.db ".read sql/user_hobbies.sql"
echo Creating USER_COMMENT...
sqlite3 TrainingApp.db ".read sql/USER_COMMENT.sql"
echo Creating METRICS...
sqlite3 TrainingApp.db ".read sql/METRICS.sql"
popd

pause